/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/v1/advisories/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crop advisory for a cell, lead and crop */
        post: operations["evaluate_api_v1_advisories_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drought/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk for one cell by row/col or GPS */
        get: operations["cell_risk_api_v1_drought_cell_get"];
        put?: never;
        /** Risk for one cell (JSON body) */
        post: operations["cell_risk_post_api_v1_drought_cell_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drought/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gridded drought probability for one lead */
        get: operations["drought_map_api_v1_drought_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enso/outlook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Niño 3.4 history and CNN-LSTM forecast */
        get: operations["outlook_api_v1_enso_outlook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: process is up (200 even when degraded) */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: 503 until forecasts can be served */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AdvisoryRequest */
        AdvisoryRequest: {
            /**
             * Col
             * @description Watershed grid column index (west = 0)
             */
            col?: number | null;
            /**
             * Crop
             * @description Target staple crop
             * @default tef
             * @enum {string}
             */
            crop: "tef" | "wheat" | "maize";
            /**
             * Iek Agrees
             * @description Indigenous ecological knowledge: True = local indicators agree with a dry outlook
             */
            iek_agrees?: boolean | null;
            /**
             * Latitude
             * @description GPS latitude (alternative to row/col)
             */
            latitude?: number | null;
            /**
             * Lead Month
             * @description Forecast lead time in months
             * @default 1
             */
            lead_month: number;
            /**
             * Longitude
             * @description GPS longitude (alternative to row/col)
             */
            longitude?: number | null;
            /**
             * Row
             * @description Watershed grid row index (north = 0)
             */
            row?: number | null;
        };
        /** AdvisoryResponse */
        AdvisoryResponse: {
            /** Adjusted Probability */
            adjusted_probability: number;
            /** Col */
            col: number;
            /** Confidence Level */
            confidence_level: string;
            /**
             * Crop
             * @enum {string}
             */
            crop: "tef" | "wheat" | "maize";
            /** Crop Note */
            crop_note: string;
            /** Crop Recommendation */
            crop_recommendation: string;
            /** Enso State */
            enso_state: string;
            /** Iek Assessment */
            iek_assessment: string;
            /** Lead Month */
            lead_month: number;
            /** Planting Window */
            planting_window: string;
            /** Preparedness Action */
            preparedness_action: string;
            provenance: components["schemas"]["ForecastProvenance"];
            /** Raw Probability */
            raw_probability: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "Low" | "Moderate" | "High" | "Severe";
            /** Row */
            row: number;
            /**
             * Rules Version
             * @description Version of the advisory rule set (ai_drews.advisory.RULES_VERSION)
             */
            rules_version: string;
            /** Season */
            season: string;
            /** Target Date */
            target_date: string;
            /** Water Management */
            water_management: string;
        };
        /** CacheStatus */
        CacheStatus: {
            /** Backend */
            backend: string;
            /** Reachable */
            reachable: boolean;
        };
        /**
         * CellRiskQuery
         * @description Either (row, col) or (latitude, longitude). Neither -> watershed centre cell.
         */
        CellRiskQuery: {
            /** Col */
            col?: number | null;
            /** Latitude */
            latitude?: number | null;
            /**
             * Lead Month
             * @default 1
             */
            lead_month: number;
            /** Longitude */
            longitude?: number | null;
            /** Row */
            row?: number | null;
        };
        /** CellRiskResponse */
        CellRiskResponse: {
            /** Col */
            col: number;
            /** Latitude */
            latitude: number;
            /** Lead Month */
            lead_month: number;
            /** Longitude */
            longitude: number;
            /** Probability */
            probability: number;
            provenance: components["schemas"]["ForecastProvenance"];
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "Low" | "Moderate" | "High" | "Severe";
            /** Row */
            row: number;
        };
        /** DroughtMapResponse */
        DroughtMapResponse: {
            /**
             * Bbox
             * @description lon_min, lat_min, lon_max, lat_max
             */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Cells */
            cells: components["schemas"]["GridCellRisk"][];
            /** Grid Shape */
            grid_shape: [
                number,
                number
            ];
            /**
             * Issued Date
             * @description Issue month, e.g. 'June 2026'
             */
            issued_date: string;
            /** Lead Month */
            lead_month: number;
            /** Max Probability */
            max_probability: number;
            /** Mean Probability */
            mean_probability: number;
            /** Min Probability */
            min_probability: number;
            /** Probabilities */
            probabilities: number[][];
            provenance: components["schemas"]["ForecastProvenance"];
            /**
             * Target Date
             * @description Target month, e.g. 'July 2026'
             */
            target_date: string;
        };
        /** EnsoOutlookResponse */
        EnsoOutlookResponse: {
            /** Current Nino34 */
            current_nino34: number;
            /**
             * Current State
             * @description El Niño | La Niña | Neutral
             */
            current_state: string;
            /** Forecast Horizon Months */
            forecast_horizon_months: number;
            /**
             * Forecast Series
             * @description Empty when the ENSO model has not been trained
             */
            forecast_series: components["schemas"]["EnsoPoint"][];
            /** Historical Series */
            historical_series: components["schemas"]["EnsoPoint"][];
            provenance: components["schemas"]["ForecastProvenance"];
            /** Teleconnection Summary */
            teleconnection_summary: string;
        };
        /** EnsoPoint */
        EnsoPoint: {
            /**
             * Date
             * @description YYYY-MM
             */
            date: string;
            /**
             * Is Forecast
             * @default false
             */
            is_forecast: boolean;
            /** Nino34 */
            nino34: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * ForecastProvenance
         * @description Attached to every forecast-derived response so clients can show where the numbers come from.
         */
        ForecastProvenance: {
            /**
             * Data Source
             * @description 'real' or 'synthetic' training data, as recorded in drought_meta.json
             */
            data_source: string;
            /**
             * Issued Date
             * @description Last month of input data the forecast is issued from (YYYY-MM-DD)
             */
            issued_date: string;
            /**
             * Model Version
             * @description Version string written by `ai-drews train drought`
             */
            model_version: string;
            /**
             * Source
             * @description Live inference or last precomputed raster
             * @enum {string}
             */
            source: "model" | "precomputed";
        };
        /** GridCellRisk */
        GridCellRisk: {
            /** Col */
            col: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Probability */
            probability: number;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "Low" | "Moderate" | "High" | "Severe";
            /** Row */
            row: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Auth Enabled */
            auth_enabled: boolean;
            cache: components["schemas"]["CacheStatus"];
            /** Environment */
            environment: string;
            model: components["schemas"]["ModelStatus"];
            /** Service */
            service: string;
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unavailable";
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelStatus */
        ModelStatus: {
            /** Data Source */
            data_source?: string | null;
            /**
             * Enso Forecast Available
             * @default false
             */
            enso_forecast_available: boolean;
            /** Issued Date */
            issued_date?: string | null;
            /** Loaded */
            loaded: boolean;
            /** Model Version */
            model_version?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "model" | "precomputed" | "unavailable";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    evaluate_api_v1_advisories_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvisoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisoryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Model unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cell_risk_api_v1_drought_cell_get: {
        parameters: {
            query?: {
                col?: number | null;
                latitude?: number | null;
                /** @description Forecast lead time (1, 2 or 3 months) */
                lead_month?: number;
                longitude?: number | null;
                row?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellRiskResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Model unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cell_risk_post_api_v1_drought_cell_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CellRiskQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellRiskResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Model unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    drought_map_api_v1_drought_map_get: {
        parameters: {
            query?: {
                /** @description Forecast lead time (1, 2 or 3 months) */
                lead_month?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DroughtMapResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Model unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    outlook_api_v1_enso_outlook_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnsoOutlookResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Model unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
